onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /mp3_tb/dut/pc_out
add wave -noupdate /mp3_tb/dut/ir_out
add wave -noupdate /mp3_tb/dut/issue_control/adj9_out
add wave -noupdate /mp3_tb/dut/issue_control/curr_pc
add wave -noupdate /mp3_tb/dut/issue_control/instr_is_new
add wave -noupdate /mp3_tb/dut/alu_RS/CDB_arbiter/RS_CDB_in
add wave -noupdate /mp3_tb/dut/alu_RS/CDB_arbiter/RS_flush
add wave -noupdate /mp3_tb/dut/alu_RS/CDB_arbiter/CDB_out
add wave -noupdate /mp3_tb/dut/alu_RS/CDB_arbiter/i
add wave -noupdate /mp3_tb/dut/alu_RS/CDB_arbiter/pri_en_valid
add wave -noupdate /mp3_tb/dut/alu_RS/CDB_arbiter/pri_en_out
add wave -noupdate /mp3_tb/dut/alu_RS/RS_decoder/ld_busy
add wave -noupdate /mp3_tb/dut/alu_RS/RS_decoder/issue_ld_Vj
add wave -noupdate /mp3_tb/dut/alu_RS/RS_decoder/issue_ld_Vk
add wave -noupdate /mp3_tb/dut/alu_RS/RS_decoder/issue_ld_Qk
add wave -noupdate /mp3_tb/dut/alu_RS/RS_decoder/issue_ld_Qj
add wave -noupdate /mp3_tb/dut/alu_RS/RS_decoder/res_station_id
add wave -noupdate /mp3_tb/dut/alu_RS/RS_decoder/RS_ld_busy
add wave -noupdate /mp3_tb/dut/alu_RS/RS_decoder/RS_issue_ld_Vj
add wave -noupdate /mp3_tb/dut/alu_RS/RS_decoder/RS_issue_ld_Vk
add wave -noupdate /mp3_tb/dut/alu_RS/RS_decoder/RS_issue_ld_Qk
add wave -noupdate /mp3_tb/dut/alu_RS/RS_decoder/RS_issue_ld_Qj
add wave -noupdate /mp3_tb/dut/alu_RS/flush
add wave -noupdate /mp3_tb/dut/alu_RS/op_in
add wave -noupdate /mp3_tb/dut/alu_RS/bit5
add wave -noupdate /mp3_tb/dut/alu_RS/CDB_in
add wave -noupdate /mp3_tb/dut/alu_RS/Vj
add wave -noupdate /mp3_tb/dut/alu_RS/Vk
add wave -noupdate /mp3_tb/dut/alu_RS/Qj
add wave -noupdate /mp3_tb/dut/alu_RS/Qk
add wave -noupdate /mp3_tb/dut/alu_RS/dest
add wave -noupdate /mp3_tb/dut/alu_RS/ld_busy
add wave -noupdate /mp3_tb/dut/alu_RS/issue_ld_Vj
add wave -noupdate /mp3_tb/dut/alu_RS/issue_ld_Vk
add wave -noupdate /mp3_tb/dut/alu_RS/issue_ld_Qk
add wave -noupdate /mp3_tb/dut/alu_RS/issue_ld_Qj
add wave -noupdate /mp3_tb/dut/alu_RS/res_station_id
add wave -noupdate /mp3_tb/dut/alu_RS/load_buffer_CDB_out
add wave -noupdate /mp3_tb/dut/alu_RS/busy_out
add wave -noupdate /mp3_tb/dut/alu_RS/CDB_out
add wave -noupdate /mp3_tb/dut/alu_RS/ld_buffer_flush
add wave -noupdate /mp3_tb/dut/alu_RS/RS_flush
add wave -noupdate /mp3_tb/dut/alu_RS/RS_ld_busy
add wave -noupdate /mp3_tb/dut/alu_RS/RS_issue_ld_Vj
add wave -noupdate /mp3_tb/dut/alu_RS/RS_issue_ld_Vk
add wave -noupdate /mp3_tb/dut/alu_RS/RS_issue_ld_Qk
add wave -noupdate /mp3_tb/dut/alu_RS/RS_issue_ld_Qj
add wave -noupdate /mp3_tb/dut/alu_RS/RS_CDB_out
add wave -noupdate /mp3_tb/dut/wr_control/data_width
add wave -noupdate /mp3_tb/dut/wr_control/tag_width
add wave -noupdate /mp3_tb/dut/wr_control/clk
add wave -noupdate /mp3_tb/dut/wr_control/valid_in
add wave -noupdate /mp3_tb/dut/wr_control/opcode_in
add wave -noupdate /mp3_tb/dut/wr_control/dest_in
add wave -noupdate /mp3_tb/dut/wr_control/value_in
add wave -noupdate /mp3_tb/dut/wr_control/predict_in
add wave -noupdate /mp3_tb/dut/wr_control/dest_a
add wave -noupdate /mp3_tb/dut/wr_control/value_out
add wave -noupdate /mp3_tb/dut/wr_control/ld_regfile_value
add wave -noupdate /mp3_tb/dut/wr_control/ld_regfile_busy
add wave -noupdate /mp3_tb/dut/wr_control/RE_out
add wave -noupdate /mp3_tb/dut/wr_control/flush
add wave -noupdate /mp3_tb/dut/wr_control/pcmux_sel
add wave -noupdate /mp3_tb/dut/wr_control/new_pc
add wave -noupdate /mp3_tb/dut/wr_control/ld_cc
add wave -noupdate /mp3_tb/dut/wr_control/gencc_out
add wave -noupdate /mp3_tb/dut/wr_control/cc_out
add wave -noupdate /mp3_tb/dut/wr_control/branch_enable
add wave -noupdate /mp3_tb/dut/reorder_buffer/ROB/inst_out
add wave -noupdate /mp3_tb/dut/reorder_buffer/ROB/dest_out
add wave -noupdate /mp3_tb/dut/reorder_buffer/ROB/valid_out
add wave -noupdate /mp3_tb/dut/reorder_buffer/ROB/value_out
add wave -noupdate /mp3_tb/dut/reorder_buffer/ROB/predict_out
add wave -noupdate /mp3_tb/dut/reorder_buffer/ROB/addr_out
add wave -noupdate /mp3_tb/dut/reorder_buffer/ROB/r_addr
add wave -noupdate /mp3_tb/dut/reorder_buffer/ROB/w_addr
add wave -noupdate /mp3_tb/dut/reorder_buffer/inst
add wave -noupdate /mp3_tb/dut/reorder_buffer/ld_value
add wave -noupdate /mp3_tb/dut/reorder_buffer/ld_dest
add wave -noupdate /mp3_tb/dut/reorder_buffer/ld_inst
add wave -noupdate /mp3_tb/dut/reorder_buffer/ld_valid
add wave -noupdate /mp3_tb/dut/reorder_buffer/ld_predict
add wave -noupdate /mp3_tb/dut/reorder_buffer/value_in
add wave -noupdate /mp3_tb/dut/issue_control/rob_value_in
add wave -noupdate -expand /mp3_tb/dut/reorder_buffer/ROB/value
add wave -noupdate /mp3_tb/dut/reorder_buffer/ROB/dest
add wave -noupdate -expand /mp3_tb/dut/reorder_buffer/ROB/inst
add wave -noupdate /mp3_tb/dut/reorder_buffer/ROB/valid
add wave -noupdate /mp3_tb/dut/reorder_buffer/ROB/predict
add wave -noupdate /mp3_tb/dut/reorder_buffer/ROB/cnt
add wave -noupdate /mp3_tb/dut/reorder_buffer/ROB/full
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {5388 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 213
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 2
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {210 ns}
